// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhjxnkrnrlzqkbxxdmrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoanhua3Jucmx6cWtieHhkbXJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzgzMTksImV4cCI6MjA2OTQ1NDMxOX0.fOoFmz9yGDVQYl-O937eea9jP83djiPMoTRbG0kUPRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});